apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: node-service
          servicePort: 3000
      - path: /
        backend:
          serviceName: node-service
          servicePort: 3000

